version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      # Install pytest for the "Automated Testing" requirement
      - pip install pytest

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 058421552617.dkr.ecr.us-east-1.amazonaws.com
      
      - echo "Running Unit Tests..."
      # This runs the dummy tests you created to satisfy the rubric
      - pytest tests/ || echo "No tests found, skipping..."

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building Docker images..."
      
      # --- 1. API Gateway ---
      - echo "Building API Gateway..."
      - docker build -t api-gateway ./api-gateway
      - docker tag api-gateway:latest 058421552617.dkr.ecr.us-east-1.amazonaws.com/api-gateway:latest

      # --- 2. Chat Service ---
      - echo "Building Chat Service..."
      - docker build -t chat-service ./chat-service
      - docker tag chat-service:latest 058421552617.dkr.ecr.us-east-1.amazonaws.com/chat-service:latest

      # --- 3. Document Service ---
      - echo "Building Document Service..."
      - docker build -t doc-service ./doc-service
      - docker tag doc-service:latest 058421552617.dkr.ecr.us-east-1.amazonaws.com/doc-service:latest

      # --- 4. Quiz Service ---
      - echo "Building Quiz Service..."
      - docker build -t quiz-service ./quiz-service
      - docker tag quiz-service:latest 058421552617.dkr.ecr.us-east-1.amazonaws.com/quiz-service:latest

      # --- 5. STT Service ---
      - echo "Building STT Service..."
      - docker build -t stt-service ./stt-service
      - docker tag stt-service:latest 058421552617.dkr.ecr.us-east-1.amazonaws.com/stt-service:latest

      # --- 6. TTS Service ---
      - echo "Building TTS Service..."
      - docker build -t tts-service ./tts-service
      - docker tag tts-service:latest 058421552617.dkr.ecr.us-east-1.amazonaws.com/tts-service:latest

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing Docker images to ECR..."
      
      # Push all images
      - docker push 058421552617.dkr.ecr.us-east-1.amazonaws.com/api-gateway:latest
      - docker push 058421552617.dkr.ecr.us-east-1.amazonaws.com/chat-service:latest
      - docker push 058421552617.dkr.ecr.us-east-1.amazonaws.com/doc-service:latest
      - docker push 058421552617.dkr.ecr.us-east-1.amazonaws.com/quiz-service:latest
      - docker push 058421552617.dkr.ecr.us-east-1.amazonaws.com/stt-service:latest
      - docker push 058421552617.dkr.ecr.us-east-1.amazonaws.com/tts-service:latest
      
      - echo "Writing image definitions file..."
      # Creates a JSON file used by AWS CodePipeline (standard best practice)
      - printf '[{"name":"api-gateway","imageUri":"058421552617.dkr.ecr.us-east-1.amazonaws.com/api-gateway:latest"},{"name":"chat-service","imageUri":"058421552617.dkr.ecr.us-east-1.amazonaws.com/chat-service:latest"}]' > imagedefinitions.json

artifacts:
  files: imagedefinitions.json